### ISSUE TITLE
iframe is not a self-closing tag

### ISSUE THREAD

**Issue by philip-bl** [kmonsoor/embedX#4]
embedX generates the following iframe code for youtube link:

`'<iframe id="embedx-yt" type="text/html" width="640" height="390" position="center" src="http://www.youtube.com/embed/Diuv3XZQXyc" frameborder="0"/>'`

However iframe is not a self-closing link. As a result, this does not work as intended at least in chrome and firefox on ubuntu. All elements after this iframe get erased.

The code should be like this:
`'<iframe id="embedx-yt" type="text/html" width="640" height="390" position="center" src="http://www.youtube.com/embed/Diuv3XZQXyc" frameborder="0"></iframe>'`

**Comment by kmonsoor** [comment]
fixed by #5
